name: Build and push image to Docker Hub with it's description

on:
  repository_dispatch:
    types:
      - 'build_latest'

jobs:
  docker:
    runs-on: ubuntu-latest
    env:
      project_name: ghz
    steps:
      - name: Cache Docker build layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Get the tag
        id: tag_name
        run: echo ::set-output name=version::${GITHUB_REF/refs\/tags\//}

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and push latest
        id: docker_build_latest
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          builder: ${{ steps.buildx.outputs.name }}
          tags:  ${{ github.repository_owner }}/${{ env.project_name }}:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          build-args:
            - "APP_VERSION=${{ steps.tag_name.outputs.version }}"

      - name: Update Docker Hub description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          repository: ${{ github.repository_owner }}/${{ env.project_name }}
